const TableData = [
    // {
    //     aiPolicyName: "AI Act",
    //     country: "European Union",
    //     governingBody: "European Commission",
    //     announcementYear: 2021,
    //     status: "Launched",
    //     Whitepaper_Document_Link: "AI Act Proposal",
    // },
    // {
    //     aiPolicyName: "AI Bill of Rights",
    //     country: "United States",
    //     governingBody: "White House / Office of Science and Technology Policy",
    //     announcementYear: 2022,
    //     status: "Research",
    //     Whitepaper_Document_Link: "AI Bill of Rights",
    // },
    // {
    //     aiPolicyName: "New Generation Artificial Intelligence Development Plan",
    //     country: "China",
    //     governingBody: "State Council of China",
    //     announcementYear: 2012,
    //     status: "Launched",
    //     Whitepaper_Document_Link: "Development Plan",
    // },
    // {
    //     aiPolicyName: "Directive on Automated Decision-Making",
    //     country: "Canada",
    //     governingBody: "Government of Canada",
    //     announcementYear: 2020,
    //     status: "Launched",
    //     Whitepaper_Document_Link:
    //         "<b>Directive on Automated Decision-Making</b>",
    // },
    // {
    //     aiPolicyName: "AI Ethics Framework",
    //     country: "Australia",
    //     governingBody: "Australian Government",
    //     announcementYear: 2015,
    //     status: "Launched",
    //     Whitepaper_Document_Link: "AI Ethics Framework",
    // },
    // {
    //     aiPolicyName: "AI Principles",
    //     country: "United Kingdom",
    //     governingBody: "UK Government",
    //     announcementYear: 2012,
    //     status: "Research",
    //     Whitepaper_Document_Link: "AI Principles",
    // },
    // {
    //     aiPolicyName: "AI Utilization Strategy",
    //     country: "Japan",
    //     governingBody: "Japanese Government",
    //     announcementYear: 2012,
    //     status: "Launched",
    //     Whitepaper_Document_Link: "AI Utilization Strategy",
    // },
    // {
    //     aiPolicyName: "Algorithmic Accountability Act",
    //     country: "United States",
    //     governingBody: "US Congress",
    //     announcementYear: "2019 (Proposed)",
    //     status: "Research",
    //     Whitepaper_Document_Link: "Algorithmic Accountability Act",
    // },
    // {
    //     aiPolicyName: "AI Guidelines",
    //     country: "South Korea",
    //     governingBody: "South Korean Government",
    //     announcementYear: 2012,
    //     status: "Launched",
    //     Whitepaper_Document_Link: "AI Guidelines",
    // },
    // {
    //     aiPolicyName: "Artificial Intelligence and Data Act",
    //     country: "Canada",
    //     governingBody: "Government of Canada",
    //     announcementYear: "2023 (Proposed)",
    //     status: "Development",
    //     Whitepaper_Document_Link: "AI and Data Act",
    // },
];

export default TableData;
